In [1]:
import geopandas
import pandas as pd

In [2]:
#pd.set_option('display.width', 1000)

In [3]:
url = "https://data.gov.au/geoserver/audit-2019-congestion-on-all-roads-during-2031-pm-peak/wfs?request=GetFeature&typeName=ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604&outputFormat=json"
df = geopandas.read_file(url)

In [4]:
df.head(20)

,id,route,direction,segment,speed,volume,vcr,vcr_cat,geometry
0,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.1,None,None,None,40,1000,0.3,Low,"MULTILINESTRING ((149.11357 -35.18028, 149.113..."
1,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.2,None,None,None,45,1000,0.1,Low,"MULTILINESTRING ((149.11425 -35.17961, 149.114..."
2,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.3,None,None,None,40,1000,0.7,Medium,"MULTILINESTRING ((149.09400 -35.46410, 149.094..."
3,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.4,None,None,None,45,1000,0.3,Low,"MULTILINESTRING ((149.09402 -35.46485, 149.094..."
4,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.5,Drakeford Dve/Tuggeranong Pky/Parkes Way Corridor,Southbound,Taverner St to Erindale Dve (Drakeford Dve),60,3000,0.7,Medium,"MULTILINESTRING ((149.07477 -35.40304, 149.074..."
5,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.6,None,None,None,35,1000,0.6,Low,"MULTILINESTRING ((149.12936 -35.28296, 149.129..."
6,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.7,None,None,None,40,1000,0.2,Low,"MULTILINESTRING ((149.10978 -35.43789, 149.109..."
7,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.8,None,None,None,35,1000,0.5,Low,"MULTILINESTRING ((149.11104 -35.43679, 149.110..."
8,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.9,None,None,None,35,1000,0.6,Low,"MULTILINESTRING ((149.12862 -35.28312, 149.128..."
9,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.10,None,None,None,40,1000,0.3,Low,"MULTILINESTRING ((149.10978 -35.43789, 149.109..."
10,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.11,None,None,None,40,1000,0.1,Low,"MULTILINESTRING ((149.11018 -35.43847, 149.109..."
11,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.12,None,None,None,50,1000,0.1,Low,"MULTILINESTRING ((149.10025 -35.41215, 149.100..."
12,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.13,None,None,None,50,1000,0.2,Low,"MULTILINESTRING ((149.10036 -35.41196, 149.100..."
13,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.14,Drakeford Dve/Tuggeranong Pky/Parkes Way Corridor,Southbound,Edinburgh Ave to Clunies Ross St (Parkes Way),45,6000,0.9,Medium,"MULTILINESTRING ((149.12114 -35.28591, 149.120..."
14,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.15,None,None,None,90,1000,0.3,Low,"MULTILINESTRING ((149.25056 -35.15723, 149.250..."
15,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.16,None,None,None,95,1000,0.1,Low,"MULTILINESTRING ((149.24666 -35.11091, 149.246..."
16,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.17,None,None,None,50,1000,0.2,Low,"MULTILINESTRING ((149.10025 -35.41215, 149.100..."
17,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.18,None,None,None,50,1000,0.1,Low,"MULTILINESTRING ((149.09996 -35.41248, 149.100..."
18,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.19,Athllon Dve/Commonwealth Ave Corridor,Northbound,King Edward Tce to Parkes Way (Commonwealth Ave),45,7000,0.8,Medium,"MULTILINESTRING ((149.12733 -35.28957, 149.127..."
19,ckan_cdd116c9_9cbb_4f35_a4b1_876029c2b604.20,East-West Corridors (Hindmarsh Dve),Westbound,Yamba Dve to Melrose Dve (Hindmarsh Dve),40,4000,0.7,Medium,"MULTILINESTRING ((149.09405 -35.34919, 149.093..."

In [5]:
df.to_csv("RoadCongestion.csv")

In [6]:
df.dtypes

id             object
route          object
direction      object
segment        object
speed           int64
volume          int64
vcr           float64
vcr_cat        object
geometry     geometry
dtype: object

In [7]:
df.info(memory_usage='deep')

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 226227 entries, 0 to 226226
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         226227 non-null  object
 1   route      35352 non-null   object
 2   direction  35234 non-null   object
 3   segment    35172 non-null   object
 4   speed      226227 non-null  int64
 5   volume     226227 non-null  int64
 6   vcr        226227 non-null  float64
 7   vcr_cat    226227 non-null  object
 8   geometry   226227 non-null  geometry
dtypes: float64(1), geometry(1), int64(2), object(5)
memory usage: 64.4 MB

In [9]:
df["geometry"] = df["geometry"].astype(str)

MemoryError: Unable to allocate array with shape (226227,) and data type <U32864

In [10]:
new = df["geometry"].str.split(expand = True)

AttributeError: 'GeometryDtype' object has no attribute 'base'

In [ ]:
df1["long"] = new[1]
df1["lat"] = new[2]

In [ ]:
df1['long'] = df1['long'].str.replace('(', '')
df1['lat'] = df1['lat'].str.replace(',', '')

In [ ]:
df.to_csv("RoadCongestionClean.csv")

In [ ]:
city_name1 = []
for index, row in df.iterrows():
    
    long = row["long"]
    lat = row["lat"]
    
    
    cities1 = citipy.nearest_city(lat, long)
    city_name.append(cities1.city_name)

df1["city"] = city_name1

In [49]:
url2 = "https://data.gov.au/geoserver/audit-2019-crowding-on-suburban-trains-during-2031-pm-peak/wfs?request=GetFeature&typeName=ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca&outputFormat=json"
df2 = geopandas.read_file(url2)

In [50]:
df2.head(20)

,id,route,direction,segment,volume,vcr,vcr_cat,geometry
0,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1,None,None,None,5000,0.7,Medium,"MULTILINESTRING ((138.58275 -34.94158, 138.582..."
1,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.2,None,None,None,2000,0.3,Low,"MULTILINESTRING ((138.58306 -34.94340, 138.582..."
2,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.3,None,None,None,2000,0.5,Low,"MULTILINESTRING ((138.53664 -34.87621, 138.536..."
3,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.4,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.52935 -34.87048, 138.529..."
4,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.5,None,None,None,1000,0.2,Low,"MULTILINESTRING ((138.59747 -34.96621, 138.597..."
5,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.6,None,None,None,1000,0.5,Low,"MULTILINESTRING ((138.59033 -34.95866, 138.590..."
6,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.7,None,None,None,1000,0.5,Low,"MULTILINESTRING ((138.58645 -34.95443, 138.587..."
7,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.8,None,None,None,1000,0.2,Low,"MULTILINESTRING ((138.59033 -34.95866, 138.590..."
8,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.9,None,None,None,1000,0.4,Low,"MULTILINESTRING ((138.56201 -34.99009, 138.561..."
9,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.10,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.56197 -34.99329, 138.561..."
10,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.11,None,None,None,1000,0.4,Low,"MULTILINESTRING ((138.56584 -35.01752, 138.565..."
11,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.12,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.56793 -35.02203, 138.567..."
12,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.13,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.48764 -35.17869, 138.484..."
13,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.14,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.48350 -35.18933, 138.483..."
14,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.15,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.60538 -34.99579, 138.605..."
15,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.16,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.61115 -34.98361, 138.611..."
16,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.17,None,None,None,2000,0.3,Low,"MULTILINESTRING ((138.58498 -34.95170, 138.584..."
17,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.18,None,None,None,5000,0.7,Medium,"MULTILINESTRING ((138.58306 -34.94340, 138.583..."
18,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.19,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.49239 -35.14024, 138.491..."
19,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.20,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.48764 -35.17869, 138.488..."

In [14]:
#df2.sort_values("segment")

,id,route,direction,segment,volume,vcr,vcr_cat,geometry
1988,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1983,None,None,Adamstown to Broadmeadow,2000,0.2,Low,"MULTILINESTRING ((151.72006 -32.93374, 151.720..."
1941,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1938,Sydney to Central Coast - Train,Southbound,Adamstown to Kotara,2000,0.2,Low,"MULTILINESTRING ((151.72006 -32.93374, 151.719..."
1463,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1460,None,None,Albion Park to Dapto,1000,0.1,Low,"MULTILINESTRING ((150.79877 -34.56299, 150.798..."
1467,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1463,None,None,Albion Park to Oak Flats,2000,0.4,Low,"MULTILINESTRING ((150.79877 -34.56299, 150.799..."
925,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.924,Train (Bowen Hills - Domestic Airport),Southbound,Albion to Bowen hills,4000,0.1,Low,"MULTILINESTRING ((153.03775 -27.44273, 153.037..."
...,...,...,...,...,...,...,...,...
1967,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1963,None,None,None,1000,0.1,Low,"MULTILINESTRING ((151.71025 -32.88758, 151.710..."
1968,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1964,None,None,None,2000,0.2,Low,"MULTILINESTRING ((151.73187 -32.90284, 151.731..."
2000,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1997,None,None,None,1000,0.1,Low,"MULTILINESTRING ((151.73187 -32.90284, 151.732..."
2003,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.2003,None,None,None,1000,0.1,Low,"MULTILINESTRING ((151.74326 -32.91346, 151.743..."
2004,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.2004,None,None,None,2000,0.2,Low,"MULTILINESTRING ((151.74659 -32.91658, 151.743..."

In [51]:
df2.dtypes

id             object
route          object
direction      object
segment        object
volume          int64
vcr           float64
vcr_cat        object
geometry     geometry
dtype: object

In [52]:
df2["geometry"] = df2["geometry"].astype(str)

In [65]:
new = df2["geometry"].str.split(expand = True)

In [74]:
new

,0,1,2,3,4,5,6,7,8,9,...,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438
0,MULTILINESTRING,((138.582751,"-34.941576,",138.582918,"-34.942599,",138.583058,-34.943405)),None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,MULTILINESTRING,((138.583058,"-34.943405,",138.582918,"-34.942599,",138.582751,-34.941576)),None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,MULTILINESTRING,((138.536645,"-34.876212,",138.536411,"-34.876,",138.536005,"-34.875667,",138.535812,"-34.875528,",138.535331,...,None,None,None,None,None,None,None,None,None,None
3,MULTILINESTRING,((138.529348,"-34.870484,",138.52974,"-34.870825,",138.531053,"-34.871889,",138.535331,"-34.875167,",138.535812,...,None,None,None,None,None,None,None,None,None,None
4,MULTILINESTRING,((138.597471,"-34.966207,",138.597287,"-34.966013,",138.593396,"-34.961899,",138.590408,"-34.958749,",138.590382,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,MULTILINESTRING,((151.004362,"-33.817095,",151.004083,"-33.81698,",151.003799,"-33.816875,",151.003512,"-33.81678,",151.001324,...,None,None,None,None,None,None,None,None,None,None
2034,MULTILINESTRING,((151.186293,"-33.896685,",151.183457,"-33.897555,",151.183115,"-33.897643,",151.182749,-33.897694)),None,...,None,None,None,None,None,None,None,None,None,None
2035,MULTILINESTRING,((150.956349,"-33.801456,",150.955804,"-33.800998,",150.955186,"-33.800335,",150.954691,"-33.79973,",150.954174,...,None,None,None,None,None,None,None,None,None,None
2036,MULTILINESTRING,((150.951564,"-33.787398,",150.951468,"-33.786957,",150.951331,"-33.786435,",150.951255,"-33.786176,",150.95108,...,None,None,None,None,None,None,None,None,None,None
2037,MULTILINESTRING,((150.935832,"-33.774296,",150.93613,"-33.774349,",150.936578,"-33.774433,",150.937428,"-33.774574,",150.938329,...,None,None,None,None,None,None,None,None,None,None

In [68]:
df2["long"] = new[1]
df2["lat"] = new[2]

In [70]:
df2['long'] = df2['long'].str.replace('(', '')

df2['lat'] = df2['lat'].str.replace(',', '')

In [71]:
df2.head()

,id,route,direction,segment,volume,vcr,vcr_cat,geometry,long,lat
0,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1,None,None,None,5000,0.7,Medium,"MULTILINESTRING ((138.582751 -34.941576, 138.5...",138.582751,-34.941576
1,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.2,None,None,None,2000,0.3,Low,"MULTILINESTRING ((138.583058 -34.943405, 138.5...",138.583058,-34.943405
2,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.3,None,None,None,2000,0.5,Low,"MULTILINESTRING ((138.536645 -34.876212, 138.5...",138.536645,-34.876212
3,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.4,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.529348 -34.870484, 138.5...",138.529348,-34.870484
4,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.5,None,None,None,1000,0.2,Low,"MULTILINESTRING ((138.597471 -34.966207, 138.5...",138.597471,-34.966207

In [72]:
df2["city"] = ""

In [73]:
df2.head()

,id,route,direction,segment,volume,vcr,vcr_cat,geometry,long,lat,city
0,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1,None,None,None,5000,0.7,Medium,"MULTILINESTRING ((138.582751 -34.941576, 138.5...",138.582751,-34.941576,
1,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.2,None,None,None,2000,0.3,Low,"MULTILINESTRING ((138.583058 -34.943405, 138.5...",138.583058,-34.943405,
2,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.3,None,None,None,2000,0.5,Low,"MULTILINESTRING ((138.536645 -34.876212, 138.5...",138.536645,-34.876212,
3,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.4,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.529348 -34.870484, 138.5...",138.529348,-34.870484,
4,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.5,None,None,None,1000,0.2,Low,"MULTILINESTRING ((138.597471 -34.966207, 138.5...",138.597471,-34.966207,

In [18]:
from citipy import citipy

In [76]:
df2["lat"] = df2["lat"].astype(float)
df2["long"] = df2["long"].astype(float)

In [78]:
df2.dtypes

id            object
route         object
direction     object
segment       object
volume         int64
vcr          float64
vcr_cat       object
geometry      object
long         float64
lat          float64
city          object
dtype: object

In [104]:
city_name = []
for index, row in df2.iterrows():
    
    long = row["long"]
    lat = row["lat"]
    
    name = row["city"]
    
    cities = citipy.nearest_city(lat, long)
    city_name.append(cities.city_name)
    #df2 = df2.append(cities.city_name)

df2["city"] = city_name

In [99]:
len(city_name)

2038

In [106]:
df2.head(20)

,id,route,direction,segment,volume,vcr,vcr_cat,geometry,long,lat,city
0,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.1,None,None,None,5000,0.7,Medium,"MULTILINESTRING ((138.582751 -34.941576, 138.5...",138.582751,-34.941576,adelaide
1,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.2,None,None,None,2000,0.3,Low,"MULTILINESTRING ((138.583058 -34.943405, 138.5...",138.583058,-34.943405,adelaide
2,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.3,None,None,None,2000,0.5,Low,"MULTILINESTRING ((138.536645 -34.876212, 138.5...",138.536645,-34.876212,adelaide
3,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.4,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.529348 -34.870484, 138.5...",138.529348,-34.870484,adelaide
4,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.5,None,None,None,1000,0.2,Low,"MULTILINESTRING ((138.597471 -34.966207, 138.5...",138.597471,-34.966207,adelaide
5,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.6,None,None,None,1000,0.5,Low,"MULTILINESTRING ((138.590329 -34.958662, 138.5...",138.590329,-34.958662,adelaide
6,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.7,None,None,None,1000,0.5,Low,"MULTILINESTRING ((138.586454 -34.954433, 138.5...",138.586454,-34.954433,adelaide
7,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.8,None,None,None,1000,0.2,Low,"MULTILINESTRING ((138.590329 -34.958662, 138.5...",138.590329,-34.958662,adelaide
8,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.9,None,None,None,1000,0.4,Low,"MULTILINESTRING ((138.562008 -34.990093, 138.5...",138.562008,-34.990093,adelaide
9,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.10,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.561971 -34.993287, 138.5...",138.561971,-34.993287,adelaide
10,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.11,None,None,None,1000,0.4,Low,"MULTILINESTRING ((138.565841 -35.017523, 138.5...",138.565841,-35.017523,adelaide
11,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.12,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.567928 -35.022027, 138.5...",138.567928,-35.022027,adelaide
12,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.13,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.487636 -35.178695, 138.4...",138.487636,-35.178695,adelaide
13,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.14,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.483495 -35.189328, 138.4...",138.483495,-35.189328,adelaide
14,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.15,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.605383 -34.995791, 138.6...",138.605383,-34.995791,adelaide
15,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.16,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.611148 -34.983612, 138.6...",138.611148,-34.983612,adelaide
16,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.17,None,None,None,2000,0.3,Low,"MULTILINESTRING ((138.584983 -34.951701, 138.5...",138.584983,-34.951701,adelaide
17,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.18,None,None,None,5000,0.7,Medium,"MULTILINESTRING ((138.583058 -34.943405, 138.5...",138.583058,-34.943405,adelaide
18,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.19,None,None,None,1000,0.3,Low,"MULTILINESTRING ((138.492392 -35.140243, 138.4...",138.492392,-35.140243,adelaide
19,ckan_50a8f7ba_e2ab_4fda_8729_04b24430c3ca.20,None,None,None,1000,0.1,Low,"MULTILINESTRING ((138.487636 -35.178695, 138.4...",138.487636,-35.178695,adelaide

In [108]:
df2.city.unique()

array(['adelaide', 'gawler', 'melbourne', 'cranbourne', 'healesville',
       'craigieburn', 'sunbury', 'pakenham', 'somerville', 'melton',
       'perth', 'kwinana', 'mandurah', 'sydney', 'brisbane', 'gympie',
       'deception bay', 'buderim', 'nerang', 'gold coast', 'caboolture',
       'morayfield', 'nambour', 'burpengary', 'victoria point',
       'caloundra', 'gatton', 'wollongong', 'raymond terrace', 'bowral',
       'moss vale', 'mittagong', 'kiama', 'muswellbrook', 'singleton',
       'cessnock', 'newcastle', 'kurri kurri', 'lithgow'], dtype=object)

In [11]:
df2.to_csv("PTCrowding.csv")
df2.to_csv("PTCrowdingClean.csv")

In [12]:
df3 = pd.read_csv('weatherAUS.csv/weatherAUS.csv')

In [13]:
df3.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [16]:
location = df3["Location"]

0         Albury
1         Albury
2         Albury
3         Albury
4         Albury
           ...
145455     Uluru
145456     Uluru
145457     Uluru
145458     Uluru
145459     Uluru
Name: Location, Length: 145460, dtype: object